In [1]:

import pandas as pd
import numpy as np 

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [65]:
s1 = pd.Series({ #딕셔너리
    '2020-03-03' : 5000,
    '2020-03-04' : 30000,
    '2020-03-05' : 20000,
    '2020-03-06' : 15000,
})
s1.items()
s1.values
s1.keys
s1.index
list(s1.items())

s1['2222-02-22']=77000
s1
del s1['2222-02-22']
s1

array([ 5000, 30000, 20000, 15000], dtype=int64)

<bound method Series.keys of 2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
dtype: int64>

Index(['2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06'], dtype='object')

[('2020-03-03', 5000),
 ('2020-03-04', 30000),
 ('2020-03-05', 20000),
 ('2020-03-06', 15000)]

2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
2222-02-22    77000
dtype: int64

2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
dtype: int64

In [4]:
s0 = pd.Series(1)
s0 

s1_1 = pd.Series([1,2.0,3.5]) #리스트
s1_1

s1_2 = pd.Series((1,2,3)) #튜플
s1_2

s1 = pd.Series({ #딕셔너리
    '2020-03-03' : 5000,
    '2020-03-04' : 30000,
    '2020-03-05' : 20000,
    '2020-03-06' : 15000,
})

s1_3 = pd.Series(['a',1,5.0]) #문자, 실수, 정수 조합
s1_3

0    1
dtype: int64

0    1.0
1    2.0
2    3.5
dtype: float64

0    1
1    2
2    3
dtype: int64

0      a
1      1
2    5.0
dtype: object

In [9]:
s = pd.Series(range(5,10))
s

s = pd.Series(np.arange(100))
s

0    5
1    6
2    7
3    8
4    9
dtype: int64

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int32

In [10]:
s = pd.Series([1,2,3, np.nan,6,8]) #결측치 NaN은 float로 처리가 됨
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [14]:
s = pd.Series([10, 20, 30], index=[1,2,3])
s
s.index

s = pd.Series([10, 20, 30], index=['다영', '다혜', '다희'])
s
s.index

1    10
2    20
3    30
dtype: int64

Int64Index([1, 2, 3], dtype='int64')

다영    10
다혜    20
다희    30
dtype: int64

Index(['다영', '다혜', '다희'], dtype='object')

In [13]:
s.index

Index(['다영', '다혜', '다희'], dtype='object')

In [16]:
s= pd.Series([9904312,3448737,289045,2466052],
            index=["서울","부산","인천","대구"]) #dtype='object' datatype = '문자열객체'
s.index
s.index.name = '도시'

s

Index(['서울', '부산', '인천', '대구'], dtype='object')

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [21]:
s
s.values
s[1]
s['부산']

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

array([9904312, 3448737,  289045, 2466052], dtype=int64)

3448737

3448737

In [23]:
s #
s[[0,3,1,1]] #서울, 대국, 부산, 부산

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

도시
서울    9904312
대구    2466052
부산    3448737
부산    3448737
dtype: int64

In [27]:
s
s[1:3]
s[:3]
s[3:]
s.부산

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

도시
부산    3448737
인천     289045
dtype: int64

도시
서울    9904312
부산    3448737
인천     289045
dtype: int64

도시
대구    2466052
dtype: int64

3448737

In [29]:
s.index
s = pd.Series([99,89,79,69], index = s.index)
s

Index(['서울', '부산', '인천', '대구'], dtype='object', name='도시')

도시
서울    99
부산    89
인천    79
대구    69
dtype: int64

In [34]:
s= pd.Series([9904312,3448737,2890450,2466052],
            index=["서울","부산","인천","대구"]) 
s

서울    9904312
부산    3448737
인천    2890450
대구    2466052
dtype: int64

In [35]:
s
s/1000000

#s>2500000 #250e4로 표기 가능
(s>250e4) & (s<500e4)

s[(s>250e4) & (s<500e4)]

서울    9904312
부산    3448737
인천    2890450
대구    2466052
dtype: int64

서울    9.904312
부산    3.448737
인천    2.890450
대구    2.466052
dtype: float64

서울    False
부산     True
인천     True
대구    False
dtype: bool

부산    3448737
인천    2890450
dtype: int64

In [47]:
sb = pd.Series(np.arange(10), np.arange(10)+1)
### Series(value, index)
sb
sb>5
sb[sb>5]
sb[sb>5].sum() #6+7+8+9=30

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

7     6
8     7
9     8
10    9
dtype: int32

30

In [43]:
sb.index
sb[sb.index>5] #문자index는 불가능

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [48]:
num_s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
num_s2 = pd.Series([5,6,7,8], index=['b','c','d','a'])

num_s1
num_s2

num_s1 + num_s2  ## 동일한 인덱스 끼리 연산  #동일한 인덱스가 없으면 NaN 처리가 됨


a    1
b    2
c    3
d    4
dtype: int64

b    5
c    6
d    7
a    8
dtype: int64

a     9
b     7
c     9
d    11
dtype: int64

In [49]:
num_s3 = pd.Series([1,2,3,4], index=['e','f','g','a'])
num_s4 = pd.Series([5,6,7,8], index=['a','f','c','d'])

num_s3
num_s4

num_s3 - num_s4

e    1
f    2
g    3
a    4
dtype: int64

a    5
f    6
c    7
d    8
dtype: int64

a   -1.0
c    NaN
d    NaN
e    NaN
f   -4.0
g    NaN
dtype: float64

In [60]:
s
'서울' in s
'대구' not in s

## 딕셔너리의 items()함수 시리즈에서도 사용 가능 하지만 zip 형태로 출력
s.items()
list(s.items()) #리스트로 묶어주면 key value 확인 가능

for k,v in s.items():
    print('%s = %d' %(k, v) )

서울    9904312
부산    3448737
인천    2890450
대구    2466052
dtype: int64

True

False

[('서울', 9904312), ('부산', 3448737), ('인천', 2890450), ('대구', 2466052)]

서울 = 9904312
부산 = 3448737
인천 = 2890450
대구 = 2466052


In [69]:
s
s['서울'] = 100000
s
s['대구'] = 1875000
s
del s['대전']
s

서울     100000
부산    3448737
인천    2890450
대구    2466052
dtype: int64

서울     100000
부산    3448737
인천    2890450
대구    2466052
dtype: int64

서울     100000
부산    3448737
인천    2890450
대구    1875000
dtype: int64

KeyError: '대전'

In [71]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])
s1
len(s1) # Nan 값 포함
s1.size #NaN 값 포함
s1.shape #차원을 표현하기 때문에 튜플형태로 출력
s1.unique() # 중복된 값을 제거한 원소값 출력
s1.count() #NaN 값을 제거한 원소의 개수
s1.value_counts() #각원소들을 같은 값끼리 그룹을 만들고 개수를 세서 반환

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

16

16

(16,)

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

15

1.0    5
2.0    4
3.0    2
5.0    2
7.0    1
4.0    1
dtype: int64

In [72]:
a=np.array([2,2,2,2,2,np.NaN]) #결측치 1개를 포함
b=pd.Series(a)
a.mean() # np의 array를 평균 계산  - nan() 포함되면 계산 불가(nan 반환)
b.mean() # 기본 nan 값을 제외시키고 계산하도록

nan

2.0