In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [7]:
import numpy as np
import pandas as pd

## pandas 데이터 처리 및 변환 관련 함수

## 데이터 개수 세기
- 가장 간단한 분석은 개수를 세는 것임
- count()함수 이용
    - NaN 값은 세지 않음

In [12]:
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [13]:
s.count()

9

## 난수
- 난숫 : seed(값) 라는 함수를 사용할 수 있음
- seed 의미 : 난수 알고리즘에서 사용하는 기본값
    - 시드값이 같으면 동일한 난수가 발생

In [18]:
np.random.randint(5, size=4)

array([1, 1, 4, 3])

In [31]:
np.random.seed(3)#난수값을 고정하기 위해 사용 값은 3이 아니여도 상관없음(동시에 사용해야 값이 고정됨)
np.random.randint(5, size=4)

array([2, 0, 1, 3])

In [32]:
np.random.randint(5, size=4)

array([0, 0, 0, 3])