In [1]:

import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 콘솔에서 모든 출력 허용하기
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

## numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서


## 연산 함수
 - add, subtract, multiply, divide


In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.13331826 0.00364119 0.30206814 0.74541388 0.50932576]
 [0.47827227 0.71180604 0.25026569 0.95430497 0.99575335]
 [0.06156522 0.57672152 0.95278313 0.50811556 0.86334161]]


In [7]:
np.add(x,y)
np.divide(x,y)
np.multiply(x,y)
np.subtract(x,y)

array([[ 0.87718661,  1.22143355,  2.4368113 ,  3.32906031,  4.57776624],
       [ 5.48115274,  6.60353159,  7.93499967,  8.88818927,  9.86973597],
       [10.95976737, 11.41545298, 12.79469587, 13.37972301, 14.95825046]])

array([[ 0.        ,  4.51602742,  4.57863612,  9.11686982,  6.92321512],
       [10.39171048,  9.94148461,  7.48663363,  9.00708924, 10.34796803],
       [10.41919147, 26.47712355, 15.10011625, 34.23548166, 14.609959  ]])

array([[ 0.        ,  0.22143355,  0.8736226 ,  0.98718093,  2.31106498],
       [ 2.40576371,  3.62118953,  6.54499771,  7.10551414,  7.82762372],
       [ 9.59767371,  4.56998283,  9.53635042,  4.93639907, 13.41550651]])

array([[-0.87718661,  0.77856645,  1.5631887 ,  2.67093969,  3.42223376],
       [ 4.51884726,  5.39646841,  6.06500033,  7.11181073,  8.13026403],
       [ 9.04023263, 10.58454702, 11.20530413, 12.62027699, 13.04174954]])

In [4]:
# 일반으로도 동일한 연산을 얻을 수 있음
x+y
x/y
x*y
x-y

array([[ 0.13331826,  1.00364119,  2.30206814,  3.74541388,  4.50932576],
       [ 5.47827227,  6.71180604,  7.25026569,  8.95430497,  9.99575335],
       [10.06156522, 11.57672152, 12.95278313, 13.50811556, 14.86334161]])

array([[  0.        , 274.635598  ,   6.62102271,   4.0246098 ,
          7.85351998],
       [ 10.45429634,   8.42926251,  27.9702746 ,   8.38306437,
          9.03838284],
       [162.42936305,  19.07333017,  12.59468139,  25.58473116,
         16.21606072]])

array([[0.00000000e+00, 3.64118857e-03, 6.04136275e-01, 2.23624164e+00,
        2.03730302e+00],
       [2.39136133e+00, 4.27083626e+00, 1.75185981e+00, 7.63443977e+00,
        8.96178016e+00],
       [6.15652233e-01, 6.34393674e+00, 1.14333976e+01, 6.60550228e+00,
        1.20867826e+01]])

array([[-0.13331826,  0.99635881,  1.69793186,  2.25458612,  3.49067424],
       [ 4.52172773,  5.28819396,  6.74973431,  7.04569503,  8.00424665],
       [ 9.93843478, 10.42327848, 11.04721687, 12.49188444, 13.13665839]])

## 통계 함수
- 평균, 분산, 중앙, 최대값, 최소값 등등 통계 관련된 함수가 내장

In [5]:
y

array([[0.13331826, 0.00364119, 0.30206814, 0.74541388, 0.50932576],
       [0.47827227, 0.71180604, 0.25026569, 0.95430497, 0.99575335],
       [0.06156522, 0.57672152, 0.95278313, 0.50811556, 0.86334161]])

In [6]:
y.mean()
y.max()
y.min()

0.5364464393391599

0.9957533510536251

0.003641188568758613

In [12]:
np.var(y) # 분산
np.median(y) # 중간값
np.std(y) #표준편차

0.06305359765374095

0.6035315885900535

0.2511047543431644

## 집계함수
- sum: 합계
- cumsum : 누적합계

In [7]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
np.sum(x, axis=None)
np.sum(x)
np.sum(x, axis=0) #열
np.sum(x, axis=1) # 행

105

105

array([15, 18, 21, 24, 27])

array([10, 35, 60])

In [9]:
np.cumsum(x) # 각 원소의 누적 합계

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

## any, all 함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면, True 아니면 False
- all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [10]:
z = np.random.rand(10)
z

array([0.14586354, 0.69529174, 0.70315373, 0.59828604, 0.22390796,
       0.40465929, 0.00431521, 0.69474001, 0.87805099, 0.21410615])

In [11]:
z>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
np.any(z>0) # z의 원소중 0 초과하는 값이 1개라도 존재하면 True

True

In [13]:
np.all(z>0) # z의 원소 모두가 0초과하는 값이 면 True

True

In [14]:
np.all(z!=0)

True

## where 함수
- where(조건, 조건이 참일 경우, 거짓인 경우)  
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우


In [15]:
z = np.random.randn(10)
z

array([-0.76161288,  0.72565186,  0.52694361,  1.21294672,  1.62461491,
        0.17072645,  0.60456615, -0.31306456, -0.40630702,  0.93649069])

In [16]:
np.where(z>0, z, 0)

array([0.        , 0.72565186, 0.52694361, 1.21294672, 1.62461491,
       0.17072645, 0.60456615, 0.        , 0.        , 0.93649069])

In [17]:
np.where(z>0, 10, 0) # 참이면 10 거짓이면 0

array([ 0, 10, 10, 10, 10, 10, 10,  0,  0, 10])

## axis 파라미터 
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용



* axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
- 예) np.sum, np.mean, np.any 등등



In [18]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 1차원

In [19]:
# 1차원 데이터 적용
np.sum(x, axis=0)

np.sum(x, axis=1) #1차원에서 적용해서 Error 발생
#axis 1 is out of bounds for array of dimension 1


105

AxisError: axis 1 is out of bounds for array of dimension 1

## 2차원

In [20]:
y = x.reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
np.sum(y, axis=0)
np.sum(y, axis=1)
np.sum(y, axis=2) # 2차원 인데 3차원 값을 넣어서 Error 발생

array([15, 18, 21, 24, 27])

array([10, 35, 60])

AxisError: axis 2 is out of bounds for array of dimension 2

## 3차원

In [22]:
nums = np.array(
    [[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]
)

nums
nums.ndim

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

3

In [23]:
np.sum(nums, axis=0) # 위 아래 해당 값 더하기
np.sum(nums, axis=1) # 각각 열을 더해서 표시
np.sum(nums, axis=2) # 하나의 행 안에서 덧셈

array([[ 6,  8, 10],
       [12, 14, 16]])

array([[ 3,  5,  7],
       [15, 17, 19]])

array([[ 3, 12],
       [21, 30]])